### PR TITLE
Updates to latest brave and polishes build

### PR DESCRIPTION
**Pull request by codefromthecrypt**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@reta ready to save us again? :D why would PAX be unable to find these classes.. they work locally?

**Comment by reta** [comment]
@adriancole :-D , sure, will take a look shortly

**Comment by reta** [comment]
@adriancole oh ... it seems the build issue only, `+./mvnw verify -nsu` does not install Karaf features into local Maven repo, and `BraveIT` fails to find the snapshot and install the bundles

**Comment by reta** [comment]
Comes from this guys: https://github.com/openzipkin/brave-karaf/commit/e856569f1998d5a32df6938472cc7f3e439f37bb#diff-6ddac3b8d45b6fb74e039b117a7b9474c537b95569ea93180c31bde3f0d474b5

**Comment by reta** [comment]
@adriancole pushed this commit https://github.com/openzipkin/brave-karaf/pull/59/commits/80a9666f85242fa22334de7285b04d0fae2415cd, please feel free to remove it

**Comment by codefromthecrypt** [comment]
Thanks for the help @reta. Great comment!

**Pull request merged**
