### PR TITLE
Skips deployment of integration tests

### PR DESCRIPTION
**Pull request by codefromthecrypt**
See #4

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
thx for suggestion @reta will check on master

**Comment by codefromthecrypt** [comment]
this worked

```
[INFO] --- maven-deploy-plugin:2.8.2:deploy (default-deploy) @ brave-itests ---
[INFO] Skipping artifact deployment
```

**Comment by reta** [comment]
:+1: , thanks @adriancole, I am often getting an impression that you never sleep :smile:

**Comment by codefromthecrypt** [comment]
timezones have changed a lot recently. I do sleep :P

**Pull request merged**
